
name: Generate 100M TXT File

on:
  workflow_dispatch:  # 手动触发

jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create 100M TXT file
        run: |
          echo "htmlhtmlhtmlhtml" > 100M.txt
          for i in {1..6553599}; do
            echo "htmlhtmlhtmlhtml" >> 100M.txt
          done

      - name: Verify file size
        run: |
          du -h 100M.txt
          if [ $(du -m 100M.txt | cut -f1) -ge 100 ]; then
            echo "File size is at least 100M"
          else
            echo "File size is less than 100M"
            exit 1
          fi
    - name: Commit and push the file
      run: |
        git config --local user.email "3407334353@qq.com"
        git config --local user.name "dmserver"
        git add 100M.txt
        git commit -m "Add 100M file"
        git push origin main
